apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v1
  labels:
    app: webapp-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-v1
  template:
    metadata:
      labels:
        app: webapp-v1
    spec:
      containers:
        - name: webapp-v1
          image: ""  # the image name will take it automatically from the kubernetes-deployment.yaml pipeline 
          ports:
            - containerPort: 80
          securityContext:
            runAsUser: 1001                
            runAsGroup: 1001               # Use the non-root group ID
            readOnlyRootFilesystem: true   # Enforce a read-only filesystem
            allowPrivilegeEscalation: false # Prevent privilege escalation
          resources:
            requests:
              cpu: "100m"                  # Request minimal CPU
              memory: "90Mi"               # Request minimal memory
            limits:
              cpu: "500m"                  # Limit CPU usage
              memory: "128Mi"              # Limit memory usage
