apiVersion: v1
kind: Service
metadata:
  name: webapp-v1-service
  labels:
    app: webapp-v1
spec:
  selector:
    app: webapp-v1                # Match the deployment label
  ports:
    - protocol: TCP
      port: 8085                    # Expose the service on port 8085
      targetPort: 80             # Redirect traffic to container port 8080
  type: LoadBalancer               # Expose the service externally (if using cloud provider)
